
TRUNCATE TABLE Note RESTART IDENTITY CASCADE;
TRUNCATE TABLE Parametre RESTART IDENTITY CASCADE;
TRUNCATE TABLE Resolution RESTART IDENTITY CASCADE;
TRUNCATE TABLE Operateur RESTART IDENTITY CASCADE;
TRUNCATE TABLE Correcteur RESTART IDENTITY CASCADE;
TRUNCATE TABLE Matiere RESTART IDENTITY CASCADE;
TRUNCATE TABLE Candidat RESTART IDENTITY CASCADE;


CREATE DATABASE IF NOT EXISTS Fitsarana;
USE Fitsarana;
